// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:nendoroid_db/feature/nendo/model/nendo_data.dart';
import 'package:nendoroid_db/feature/scraping/model/set_data.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(NameAdapter());
    registerAdapter(NendoDataAdapter());
    registerAdapter(SeriesAdapter());
    registerAdapter(SetDataAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(NameAdapter());
    registerAdapter(NendoDataAdapter());
    registerAdapter(SeriesAdapter());
    registerAdapter(SetDataAdapter());
  }
}
